# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - deno run -A main.ts
    silent: true

  build:docker: docker build -t ayasechan/randip .

  push:docker: docker push ayasechan/randip
